version: '3'
services:
  postgres:
    image: postgres:10.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'health-diary'
      POSTGRES_PASSWORD: 'health-diary'
      POSTGRES_DB: 'health-diary'

  web:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: bash -c "nodemon src/index.js"
    links:
      - postgres
    depends_on:
      - postgres